### ISSUE TITLE
Files failed, but they looks like they finished

### ISSUE THREAD

**Issue by BKPepe** [xunil75/PyPlex#4]
Hello,
I think this isn't quite right.

Some files failed and it still shows green bar for them:
https://ctrlv.cz//shots/2017/10/31/yfGy.png

When I look at folder's bar then it is green and white:
https://ctrlv.cz//shots/2017/10/31/tm0A.png

**Comment by xunil75** [comment]
Hi Pepe, is this the Queue window?

**Comment by BKPepe** [comment]
Sorry I forgot to mention it. Yes, it is in queue tab.

**Comment by xunil75** [comment]
ok, I got a fix for that. Give me 1min.

![queue](https://user-images.githubusercontent.com/32961904/32224163-9bad0c18-be40-11e7-99a7-4d5d6c0004ec.JPG)

This should solve the issue, have a look.

**Comment by BKPepe** [comment]
Thank you! :)

**Comment by xunil75** [comment]
You need to download the file **package.js** from this repo and replace the one inside your /media/js/PyPlex/ folder. Let me know if it works at your side as well.

**Comment by xunil75** [comment]
@BKPepe can I close this issue?

**Comment by BKPepe** [comment]
It required restart of PyLoad. So that took a while, because I was downloading few files and I didn't want to type CAPTCHA again.

Right now it looks good! Thanks for your time. I really like your skin. :-)
