### ISSUE TITLE
Add package (window): too small

### ISSUE THREAD

**Issue by BKPepe** [xunil75/PyPlex#6]
Hello again,
I was quite surprised, when I wanted to add package that window, which appeared is too small.

Here I compared it against default skin:
https://ctrlv.cz/shots/2017/10/31/4RQF.png
https://ctrlv.cz/shots/2017/10/31/uk81.png

Would it be also possible to add option to resize links as it is possible in default skin?
Or it could be so small, but field for links should be more larger or there should be possibility to resize it.

I checked also pyload-next theme and I can see there is possibility to resize it.
( https://raw.githubusercontent.com/OzzieIsaacs/pyload-NextTheme/master/screenshots/adder.jpg )

**Comment by xunil75** [comment]
I'm having a look at it right now. Will fix that soon!

**Comment by xunil75** [comment]
Ok, I've fixed the issue. Please download the file **window.html** from the repo inside **/templates/PyPlex/** and replace it with yours. Reboot Pyload and delete your browser cache just to make sure.

Let me know if this fix your issue so that I can close it!

**Comment by BKPepe** [comment]
Hi,
thanks for fix, but could you please also increase length of the window "Add Package"?
Some longer urls are splitted to 2 rows.

**Comment by xunil75** [comment]
Hi Pepe, can you please explain better? Window "Add Package"? or button?
Maybe a screenshot?

**Comment by xunil75** [comment]
Do you mean the Modal-Window? If that is the case, I know what you mean. Something like this?

![add-package](https://user-images.githubusercontent.com/32961904/32274042-6252f386-bf05-11e7-8455-96190a3b0238.jpg)

I'm creating a new Theme and it will have larger Windows.

**Comment by BKPepe** [comment]
Yes. You was faster than me. I was typing it.

I'd like to have links per rows. Right now I can scale Links text-field only down and up.
So right now this link:
https://uloz.to/!BotkJq8DOA8C/s-t-d-s01e04-the-butcher-s-knife-cares-not-for-the-lamb-s-cry-rar
looks really long and it takes 3 rows:  https://ctrlv.cz/shots/2017/11/01/wY6S.png

So I'd like to extend field Links to left and right side even it will looks bad (because it will be over window "Add Package", but I'm ok with it) or a little bit increase length of window  "Add Package" as you showed

and how it looks in full hd resolution. I think right now it's too small.
https://ctrlv.cz/shots/2017/11/01/EoSM.png (I hid name of packages)

**Comment by xunil75** [comment]
Ok, I will do that modification for you only since it is more of a preference than a bug itself.

Get this file and replace it with yours, As always, reboot Pyload and delete your browser cache.


[window.zip](https://github.com/xunil75/PyPlex/files/1434059/window.zip)

**Comment by BKPepe** [comment]
Thank you very much. I will try it. I'll close a ticket.

// EDIT: Dont worry. I will. I appreciate your effort!

**Comment by xunil75** [comment]
You rather get the **"window.html"** from the repo. I have upload it. The one I have sent you is not the correct one. Sorry for the inconvenience.
