### ISSUE TITLE
[Firefox/Linux] Delay on page load before template style takes affect

### ISSUE THREAD

**Issue by jeweloper** [xunil75/PyPlex#7]
If I browse pyload with Firefox-Linux or Firefox-Android all pages are first shown without any styles for some milliseconds before the template style takes affect.
This results in a browser experience like in the late 90's, but not like a modern web application.

Steps to reproduce:
Load any pyload page with Firefox browser on any Linux based operating system (including android).

Test system:
Firefox 59.0.2
Arch Linux

Sometimes you may also notice this on Firefox-Windows. Other browsers or the classic template doesn't seem to be affected.

**Comment by xunil75** [comment]
Sorry for the delay, I was not aware of a new Issue. Which version of the Theme are you using? The one here on my repo is the original, this was however modified from the PyLoad team. Have you tried my version at all?

**Comment by jeweloper** [comment]
Hi, thx for your feedback.
I found the reason. When I compared the pyload-pyplex version of base.html file with your version, I noticed that die script references resides on the file end and not on the beginning.
When I changed this firefox didn't perform a complete page reload/rebuild when you navigate through the sub pages.
I will open the issue in pyload repository.
